# Generated by Django 2.2.6 on 2019-10-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('flight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flight_name', models.CharField(max_length=50)),
                ('time_arrival', models.DateTimeField()),
                ('time_departure', models.DateTimeField()),
                ('from_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_airport_id', to='bookticket.Airport')),
                ('to_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_airport_id', to='bookticket.Airport')),
            ],
        ),
    ]
