# Generated by Django 2.2.6 on 2019-10-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0002_flightdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightdetails',
            old_name='from_airport_id',
            new_name='from_airport',
        ),
        migrations.RenameField(
            model_name='flightdetails',
            old_name='to_airport_id',
            new_name='to_airport',
        ),
    ]
