# Generated by Django 2.2.6 on 2019-10-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0003_auto_20191026_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('confirmation', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('duty', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('passport_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookticket.Booking')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookticket.FlightDetails')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_airport', to='bookticket.Airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_airport', to='bookticket.Airport')),
            ],
        ),
    ]
