# Generated by Django 2.2.6 on 2019-10-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0004_booking_employee_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
