# Generated by Django 2.2.6 on 2019-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0005_auto_20191027_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
