# Generated by Django 2.2.6 on 2019-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0011_auto_20191027_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='False', max_length=20),
            preserve_default=False,
        ),
    ]
