# Generated by Django 2.2.6 on 2019-10-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0012_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
