# Generated by Django 2.2.6 on 2019-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookticket', '0013_remove_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='price',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
